#include "ButtonsPageBase.h"

#include <e3/ViewFactory.h>
#include "MDLiteTestValues.h"

ButtonsPageBase::ButtonsPageBase(e3::Element* pParent)
	: MDElement(pParent)
{
        this->SetOrientation((e3::EOrientation)1);
        this->SetAlignItemsVer((e3::EAlignment)0);
        this->SetBackgroundColor(MDTheme::Get()->Background);
    e3::Element* pElement1 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    AddElement(pElement1);
        pElement1->SetWidth("100%");
        pElement1->SetHeight(e3::Dim("0", "0", "0", "40", "40", "40"));
        pElement1->SetAlignItemsHor((e3::EAlignment)0);
        mBack = new MDIconButton();
        pElement1->AddElement(mBack);
        mBack->SetName(_s(arrow_back));
        mBack->SetColor(MDTheme::Get()->OnBackground);
                MDScaffold* pCustomView1 = new MDScaffold();
        AddElement(pCustomView1);
        pCustomView1->SetMarginTop(e3::Dim("0", "0", "0", "50", "50", "50"));
        pCustomView1->SetWidth(e3::Dim("100%", "100%", "100%", "500", "500", "500"));
        pCustomView1->SetHeight(e3::Dim("100%", "100%", "100%", "700", "700", "700"));
        pCustomView1->SetOrientation((e3::EOrientation)1);
        pCustomView1->SetBackgroundColor(glm::vec4(255.000000, 255.000000, 255.000000, 255.000000));
                MDAppBar* pCustomView2 = new MDAppBar();
        pCustomView1->AddElement(pCustomView2);
        pCustomView2->SetAlignItemsHor((e3::EAlignment)0);
                MDAppBarTitle* pCustomView3 = new MDAppBarTitle();
        pCustomView2->AddElement(pCustomView3);
        pCustomView3->SetText("Buttons");
    e3::Element* pElement2 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pCustomView1->AddElement(pElement2);
        pElement2->SetWidth("100%");
        pElement2->SetHeight("100%");
        pElement2->SetOrientation((e3::EOrientation)1);
        pElement2->SetScaling((e3::EScaling)1);
                MDText* pCustomView4 = new MDText();
        pElement2->AddElement(pCustomView4);
        pCustomView4->SetText("MDIconButton");
        pCustomView4->SetFontSize(e3::Dim("54", "54", "54", "18", "18", "18"));
        pCustomView4->SetFontStyle((e3::EFontStyle)2);
        pCustomView4->SetTextColor(MDTheme::Get()->OnBackground);
    e3::Element* pElement3 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement2->AddElement(pElement3);
        pElement3->SetMarginTop(10);
                MDIconButton* pCustomView5 = new MDIconButton();
        pElement3->AddElement(pCustomView5);
        pCustomView5->SetName(_s(menu));
        pCustomView5->SetColor(MDTheme::Get()->PrimaryColor);
                MDText* pCustomView6 = new MDText();
        pElement2->AddElement(pCustomView6);
        pCustomView6->SetMarginTop(40);
        pCustomView6->SetText("MDTextButton");
        pCustomView6->SetFontSize(e3::Dim("54", "54", "54", "18", "18", "18"));
        pCustomView6->SetFontStyle((e3::EFontStyle)2);
        pCustomView6->SetTextColor(MDTheme::Get()->OnBackground);
    e3::Element* pElement4 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement2->AddElement(pElement4);
        pElement4->SetMarginTop(10);
                MDTextButton* pCustomView7 = new MDTextButton();
        pElement4->AddElement(pCustomView7);
        pCustomView7->SetLabel(_s(BUTTON));
                MDTextButton* pCustomView8 = new MDTextButton();
        pElement4->AddElement(pCustomView8);
        pCustomView8->SetMarginLeft(20);
        pCustomView8->SetLabel(_s(BUTTON));
        pCustomView8->SetIcon(new MDIcon("add", 18, glm::vec4(255)));
                MDText* pCustomView9 = new MDText();
        pElement2->AddElement(pCustomView9);
        pCustomView9->SetMarginTop(40);
        pCustomView9->SetText("MDButton");
        pCustomView9->SetFontSize(e3::Dim("54", "54", "54", "18", "18", "18"));
        pCustomView9->SetFontStyle((e3::EFontStyle)2);
        pCustomView9->SetTextColor(MDTheme::Get()->OnBackground);
    e3::Element* pElement5 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement2->AddElement(pElement5);
        pElement5->SetMarginTop(10);
                MDButton* pCustomView10 = new MDButton();
        pElement5->AddElement(pCustomView10);
        pCustomView10->SetLabel(_s(BUTTON));
                MDButton* pCustomView11 = new MDButton();
        pElement5->AddElement(pCustomView11);
        pCustomView11->SetMarginLeft(20);
        pCustomView11->SetLabel(_s(BUTTON));
        pCustomView11->SetIcon(new MDIcon("add", 18, glm::vec4(255)));
                MDText* pCustomView12 = new MDText();
        pElement2->AddElement(pCustomView12);
        pCustomView12->SetMarginTop(40);
        pCustomView12->SetText("MDOutlinedButton");
        pCustomView12->SetFontSize(e3::Dim("54", "54", "54", "18", "18", "18"));
        pCustomView12->SetFontStyle((e3::EFontStyle)2);
        pCustomView12->SetTextColor(MDTheme::Get()->OnBackground);
    e3::Element* pElement6 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement2->AddElement(pElement6);
        pElement6->SetMarginTop(10);
                MDOutlinedButton* pCustomView13 = new MDOutlinedButton();
        pElement6->AddElement(pCustomView13);
        pCustomView13->SetLabel(_s(BUTTON));
                MDOutlinedButton* pCustomView14 = new MDOutlinedButton();
        pElement6->AddElement(pCustomView14);
        pCustomView14->SetMarginLeft(20);
        pCustomView14->SetLabel(_s(BUTTON));
        pCustomView14->SetIcon(new MDIcon("add", 18, MDColors::Primary::Get()));
                MDText* pCustomView15 = new MDText();
        pElement2->AddElement(pCustomView15);
        pCustomView15->SetMarginTop(40);
        pCustomView15->SetText("MDFloatingActionButton");
        pCustomView15->SetFontSize(e3::Dim("54", "54", "54", "18", "18", "18"));
        pCustomView15->SetFontStyle((e3::EFontStyle)2);
        pCustomView15->SetTextColor(MDTheme::Get()->OnBackground);
    e3::Element* pElement7 = e3::ViewFactory::CreateShape( e3::EOrientation::Horizontal);
    pElement2->AddElement(pElement7);
        pElement7->SetMarginTop(10);
                MDFloatingActionButton* pCustomView16 = new MDFloatingActionButton();
        pElement7->AddElement(pCustomView16);
        pCustomView16->SetIcon(new MDIcon("add", 18, glm::vec4(255)));
                MDFloatingActionButtonExtended* pCustomView17 = new MDFloatingActionButtonExtended();
        pElement7->AddElement(pCustomView17);
        pCustomView17->SetMarginLeft(20);
        pCustomView17->SetIcon(new MDIcon("add", 18, glm::vec4(255)));
        pCustomView17->SetLabel(_s(BUTTON));

}
